# Generated by Django 3.0.4 on 2020-04-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesync', '0002_auto_20200325_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='calendar_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='calendar_id',
            new_name='calendar',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
